# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: manages.job.wajc.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: job-operator-system
          name: job-operator-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
